name: GitHub Metrics


on:

  schedule:

    - cron: "0 0 * * *"


  workflow_dispatch:


jobs:


  metrics:


    runs-on: ubuntu-latest


    steps:


      - uses: lowlighter/metrics@latest


        with:


          filename: metrics.svg


          token: ${{ secrets.METRICS_TOKEN }}


          user: aditsiapadah


          template: classic


          base: header, activity, community, repositories


          config_timezone: Asia/Jakarta


          plugin_languages: yes


          plugin_languages_details: percentage, bytes-size


          plugin_stars: yes


          plugin_followup: yes


          plugin_projects: yes
